Compiler conformance: Quantum declaration
ORNL-QCI/qcor pull request #219
Opened 2021-09-11 15:55 UTC by moar55

This pull request conforms QASM3-MLIR conversions of quantum declarations with the latest QASM3 grammar.

2021-09-11 17:50 UTC, moar55 commented on mlir/parsers/qasm3/tests/test_quantum_declaration.cpp
> +//    qcor::execute(complex_if, "complex_if");
This line blows up memory because if of the measurement assignment statement.
If the preceding testcase is commented this works. It could be gtest doesn't do a tear down after each test?

2021-09-14 13:07 UTC, amccaskey requested changes
Summary comments: 

(1) we need to fix these diffs - a good number of the files have global changes to the whole file which makes it difficult to see what changed in the file. May need to reclone and copy changes in and re-PR.
(2) All changes to adhere to latest from upstream (at least in this case) should be additions and not modifications breaking backwards compatibility. Tests should not be updated to reflect the new syntax, but instead, you should add a new test to demonstrate and test the new syntax.

2021-09-14 13:07 UTC, amccaskey commented on mlir/parsers/qasm3/tests/test_alias_handler.cpp
> +qubit[6] q;
One thing to note - I want this implementation to conform to the qasm3.g4 spec upstream, but we are free to keep existing, or introduce novel, syntax. So in this case, yes, we should update the parser to handle `qubit[N] q`, but we should make sure that the existing `qubit q[N]` also works for our own backwards compatibility.

2021-09-14 13:07 UTC, amccaskey commented on mlir/parsers/qasm3/tests/test_compute_action.cpp
> +qubit qq;
Is this a new qasm3 spec change? Can you only have qubit declarations on a single line, no comma declarations? 

If so, I don't want that change in the compiler. The current support should be compatible with both approaches.

2021-09-14 13:07 UTC, amccaskey commented on mlir/parsers/qasm3/tests/test_optimization.cpp
> +qubit[2] q;
Going back to the comment below - instead of changing all occurrences of qubit declarations to be in the new syntax, I prefer you keep it all as is, and add a new test that shows the compiler can handle this new syntax. I'm really interested in conserving backwards compatibility with what we already have, while at the same time ensuring we are compatible with these latest changes from upstream.

2021-09-14 13:07 UTC, amccaskey commented on mlir/parsers/qasm3/tests/test_quantum_declaration.cpp
> -#include "gtest/gtest.h"
This is another case of deleting the whole file and replacing with new contents, which has messed up the diff.

2021-09-14 14:41 UTC, moar55 commented on mlir/parsers/qasm3/tests/test_compute_action.cpp
> +qubit qq;
Yes the new compiler doesn't support having a list of quantum declarations. I will update it to have backwards compatibility 👍

2021-09-14 14:42 UTC, moar55 commented on mlir/parsers/qasm3/tests/CMakeLists.txt
> -
Not sure why that happened but I will  fix it 👍

2021-09-14 15:03 UTC, moar55 commented
Would such syntax be also valid:
`qubit [4] q1, q2[3]`
@amccaskey

2021-09-14 23:46 UTC, amccaskey commented
Good question. My initial thought is no. You should be consistent in single line comma separated declarations. In the case you specify, I think qubit[4] implies a specific type (namely an array of 4 qubits) and that should be for all variables in the comma separated declaration.

2021-09-15 16:39 UTC, moar55 commented
sounds good 👍 
I also think allowing both kind of declarations for qreg would make the grammar and the implementation simpler. Given that we are not planning to adhere exactly to the openqasm 3 grammar.
So have both:
`qreg[4] q0;`
and 
`qreg q0[4];`.
It is obvious why this would make the grammar simpler. Regarding the implementation I either have to make two visitors or have a single visitor with and `std::variant` identifier list vector(one variant for 'qubit' identifier list and the other for 'qreg' identifier list). One would feel like an overkill and the other wouldn't be so clean. Atleast these are the implementations that I have in mind... @amccaskey

2021-09-20 15:59 UTC, closed without merging